---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.4
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']

- repo: local
  hooks:
  - id: isort
    name: Format with isort
    entry: poetry run isort
    language: system
    types: [python]

  - id: pyright
    name: Validate types with pyright
    entry: poetry run pyright
    pass_filenames: false
    language: system
    types: [python]
