---
version: "3.9"
services:
  bot:
    build: .
    depends_on:
      - mongo
    restart: always
    environment:
      SESANTA_BOT_TOKEN: $SESANTA_BOT_TOKEN
      SESANTA_MONGO_URI: mongodb://mongo:27017
      SESANTA_CLUB_POST_LINK: $SESANTA_CLUB_POST_LINK
      SESANTA_CLUB_BY_TELEGRAM_ID_ENDPOINT: $SESANTA_CLUB_BY_TELEGRAM_ID_ENDPOINT
      SESANTA_CLUB_TOKEN: $SESANTA_CLUB_TOKEN
      SESANTA_CRITERIA_MIN_UPVOTES: $SESANTA_CRITERIA_MIN_UPVOTES
      SESANTA_CRITERIA_MAX_CREATED_AT: $SESANTA_CRITERIA_MAX_CREATED_AT
      SESANTA_CRITERIA_MIN_MEMBERSHIP_EXPIRES_AT: $SESANTA_CRITERIA_MIN_MEMBERSHIP_EXPIRES_AT
      SESANTA_SELECTED_COUNTRY_MIN_PEOPLE: $SESANTA_SELECTED_COUNTRY_MIN_PEOPLE

  backuper:
    build:
      context: .
      dockerfile: BackupDockerfile
      args:
        DB_URI: mongodb://mongo:27017
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./dump:/dump

  mongo:
    image: mongo:7.0.2
    restart: always
    volumes:
      - ./dbdata:/data/db
